
export const BASE_URL = "http://localhost:5000/";
export const SET_LOGIN_DETAILS = "SET_LOGIN_DETAILS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const INVALID_USERNAME = "INVALID_USERNAME";
export const SET_TEAM_VALUES = "SET_TEAM_VALUES";
export const SET_VERSION_VALUES = "SET_VERSION_VALUES";
export const SET_COMMENT_VALUE = "SET_COMMENT_VALUE";
